name: Virus Scanner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    name: Run Virus Scan
    runs-on: ubuntu-latest
    if: 1 == 2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Virus Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          severity: CRITICAL,HIGH
